# Generated by Django 4.2.7 on 2023-11-19 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(blank=True, max_length=32, null=True)),
                ("city", models.CharField(blank=True, max_length=32, null=True)),
                ("state", models.CharField(blank=True, max_length=32, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("email_address", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=16, null=True)),
                ("title", models.CharField(blank=True, max_length=16, null=True)),
                ("first_name", models.CharField(blank=True, max_length=32, null=True)),
                ("middle_name", models.CharField(blank=True, max_length=32, null=True)),
                ("last_name", models.CharField(blank=True, max_length=32, null=True)),
                ("dob", models.DateField()),
                ("sex", models.CharField(choices=[("M", "Male"), ("F", "Female")], max_length=1)),
                ("booking_id", models.CharField(max_length=64, unique=True)),
                ("booking_officer", models.CharField(blank=True, max_length=64, null=True)),
                ("arresting_officer", models.CharField(blank=True, max_length=64, null=True)),
                ("details", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=32, null=True)),
                ("url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Court",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                ("address", models.CharField(max_length=32)),
                ("city", models.CharField(max_length=32)),
                ("state", models.CharField(max_length=32)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "court_type",
                    models.CharField(
                        choices=[
                            ("civil", "civil"),
                            ("criminal", "criminal"),
                            ("family", "family"),
                            ("probate", "probate"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CourtCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("case_number", models.CharField(blank=True, max_length=64, null=True)),
                ("title", models.CharField(blank=True, max_length=64, null=True)),
                ("booking", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="casemgr.booking")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Defendant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(blank=True, max_length=32, null=True)),
                ("city", models.CharField(blank=True, max_length=32, null=True)),
                ("state", models.CharField(blank=True, max_length=32, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("email_address", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=16, null=True)),
                ("title", models.CharField(blank=True, max_length=16, null=True)),
                ("first_name", models.CharField(blank=True, max_length=32, null=True)),
                ("middle_name", models.CharField(blank=True, max_length=32, null=True)),
                ("last_name", models.CharField(blank=True, max_length=32, null=True)),
                ("dob", models.DateField()),
                ("sex", models.CharField(choices=[("M", "Male"), ("F", "Female")], max_length=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Defender",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(blank=True, max_length=32, null=True)),
                ("city", models.CharField(blank=True, max_length=32, null=True)),
                ("state", models.CharField(blank=True, max_length=32, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("email_address", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=16, null=True)),
                ("title", models.CharField(blank=True, max_length=16, null=True)),
                ("first_name", models.CharField(blank=True, max_length=32, null=True)),
                ("middle_name", models.CharField(blank=True, max_length=32, null=True)),
                ("last_name", models.CharField(blank=True, max_length=32, null=True)),
                ("lawfirm", models.CharField(max_length=64)),
                ("license", models.CharField(max_length=32, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Judge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(blank=True, max_length=32, null=True)),
                ("city", models.CharField(blank=True, max_length=32, null=True)),
                ("state", models.CharField(blank=True, max_length=32, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("email_address", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=16, null=True)),
                ("title", models.CharField(blank=True, max_length=16, null=True)),
                ("first_name", models.CharField(blank=True, max_length=32, null=True)),
                ("middle_name", models.CharField(blank=True, max_length=32, null=True)),
                ("last_name", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Prosecutor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(blank=True, max_length=32, null=True)),
                ("city", models.CharField(blank=True, max_length=32, null=True)),
                ("state", models.CharField(blank=True, max_length=32, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("email_address", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=16, null=True)),
                ("title", models.CharField(blank=True, max_length=16, null=True)),
                ("first_name", models.CharField(blank=True, max_length=32, null=True)),
                ("middle_name", models.CharField(blank=True, max_length=32, null=True)),
                ("last_name", models.CharField(blank=True, max_length=32, null=True)),
                ("lawfirm", models.CharField(max_length=64)),
                ("license", models.CharField(max_length=32, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Hearing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hearing_date", models.DateField()),
                (
                    "hearing_type",
                    models.CharField(
                        choices=[
                            ("civil", "civil"),
                            ("criminal", "criminal"),
                            ("family", "family"),
                            ("probate", "probate"),
                        ],
                        max_length=32,
                    ),
                ),
                ("court_case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="casemgr.courtcase")),
                ("judge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="casemgr.judge")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="courtcase",
            name="defendant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="casemgr.defendant"),
        ),
        migrations.AddField(
            model_name="courtcase",
            name="defenders",
            field=models.ManyToManyField(to="casemgr.defender"),
        ),
        migrations.AddField(
            model_name="courtcase",
            name="files",
            field=models.ManyToManyField(to="casemgr.casefile"),
        ),
        migrations.AddField(
            model_name="courtcase",
            name="prosecutors",
            field=models.ManyToManyField(to="casemgr.prosecutor"),
        ),
    ]
