# Generated by Django 4.2.7 on 2023-11-19 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking_id", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("case_number", models.CharField(blank=True, max_length=64, null=True)),
                ("title", models.CharField(max_length=64, unique=True)),
                ("booking", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="casemgr.booking")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=32, null=True)),
                ("url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CourtType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32, unique=True)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Defendant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=16, null=True)),
                ("first_name", models.CharField(blank=True, max_length=32, null=True)),
                ("last_name", models.CharField(blank=True, max_length=32, null=True)),
                ("dob", models.DateField()),
                ("sex", models.CharField(max_length=8)),
                ("address", models.CharField(blank=True, max_length=32, null=True)),
                ("city", models.CharField(blank=True, max_length=32, null=True)),
                ("state", models.CharField(blank=True, max_length=32, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Defender",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=16, null=True)),
                ("first_name", models.CharField(blank=True, max_length=32, null=True)),
                ("last_name", models.CharField(blank=True, max_length=32, null=True)),
                ("address", models.CharField(blank=True, max_length=32, null=True)),
                ("city", models.CharField(blank=True, max_length=32, null=True)),
                ("state", models.CharField(blank=True, max_length=32, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HearingType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32, unique=True)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Judge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=16, null=True)),
                ("first_name", models.CharField(blank=True, max_length=32, null=True)),
                ("last_name", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Prosecutor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=16, null=True)),
                ("first_name", models.CharField(blank=True, max_length=32, null=True)),
                ("last_name", models.CharField(blank=True, max_length=32, null=True)),
                ("address", models.CharField(blank=True, max_length=32, null=True)),
                ("city", models.CharField(blank=True, max_length=32, null=True)),
                ("state", models.CharField(blank=True, max_length=32, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Hearing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hearing_date", models.DateField()),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="casemgr.case")),
                (
                    "hearing_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="casemgr.hearingtype"),
                ),
                ("judge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="casemgr.judge")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Court",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                ("address", models.CharField(max_length=32)),
                ("city", models.CharField(max_length=32)),
                ("state", models.CharField(max_length=32)),
                ("zip_code", models.CharField(max_length=10)),
                ("court_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="casemgr.courttype")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="case",
            name="defendant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="casemgr.defendant"),
        ),
        migrations.AddField(
            model_name="case",
            name="defenders",
            field=models.ManyToManyField(to="casemgr.defender"),
        ),
        migrations.AddField(
            model_name="case",
            name="files",
            field=models.ManyToManyField(to="casemgr.casefile"),
        ),
        migrations.AddField(
            model_name="case",
            name="prosecutors",
            field=models.ManyToManyField(to="casemgr.prosecutor"),
        ),
    ]
