# Generated by Django 4.2.7 on 2024-01-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casemgr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="total_bond",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
